import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {Providers} from '@/app/providers';
import React from 'react';
import AppNavbar from '@/app/components/navbar/navbar';
import {themesRootClasses} from '@/app/constants';
import {TrpcProvider} from '@/app/components/trpc/trpc-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={themesRootClasses.dark}>
      <body className={inter.className + ' min-h-screen text-foreground'}>
        <TrpcProvider>
          <Providers>
            <AppNavbar/>
            <main className='flex flex-col w-full mx-auto max-w-[1280px] px-6'>
              {children}
            </main>
            <footer>

            </footer>
          </Providers>
        </TrpcProvider>
      </body>
    </html>
  );
}